import MartinsConjecture
#print axioms OracleCode.exists_code
#print axioms jumpFn_gt
#print axioms halting_problem_not_partrec
#print axioms jumpP_trOracle
#print axioms Cantor.lt_jump
#print axioms Cantor.join_le
#print axioms Cantor.le_bot_iff
#print axioms Cantor.not_computable_jump
#print axioms Martin.equiv_iff_exists_equivVia
#print axioms Martin.martinLT_jump
#print axioms Martin.gamePlay_le
#print axioms Martin.cone_theorem
#print axioms Martin.cone_theorem_onCone
#print axioms trE_primrec
#print axioms jumpFn_mono
#print axioms jumpFn_congr
#print axioms Cantor.jump_congr
#print axioms Martin.orderPreserving_jump
#print axioms Martin.turingInvariant_jump
#print axioms TuringDegree.lt_jump
#print axioms Martin.eq_univ_of_isOpen_turingInvariant
#print axioms Martin.cone_dichotomy_of_isOpen
#print axioms Martin.cone_dichotomy_of_isClosed
#print axioms TuringDegree.strictMono_jump_iterate
#print axioms Martin.computablyUniformlyTuringInvariant_jump
#print axioms Martin.measurable_jump
#print axioms Martin.regular_jump
#print axioms Martin.measurableSet_cone
#print axioms Martin.onCone_forall
#print axioms Martin.martinLT_jumpIter
#print axioms Martin.martinLT_const_id
#print axioms Martin.partII_succ_provable_half
