import MartinsConjecture
#print axioms OracleCode.exists_code
#print axioms jumpFn_gt
#print axioms halting_problem_not_partrec
#print axioms jumpP_trOracle
#print axioms Cantor.lt_jump
#print axioms Cantor.join_le
#print axioms Cantor.le_bot_iff
#print axioms Cantor.not_computable_jump
#print axioms Martin.equiv_iff_exists_equivVia
#print axioms Martin.martinLT_jump
#print axioms Martin.gamePlay_le
#print axioms Martin.cone_theorem
#print axioms Martin.cone_theorem_onCone
#print axioms trE_primrec
#print axioms jumpFn_mono
#print axioms jumpFn_congr
#print axioms Cantor.jump_congr
#print axioms Martin.orderPreserving_jump
#print axioms Martin.turingInvariant_jump
#print axioms TuringDegree.lt_jump
#print axioms Martin.eq_univ_of_isOpen_turingInvariant
#print axioms Martin.cone_dichotomy_of_isOpen
#print axioms Martin.cone_dichotomy_of_isClosed
#print axioms TuringDegree.strictMono_jump_iterate
#print axioms Martin.computablyUniformlyTuringInvariant_jump
#print axioms Martin.measurable_jump
#print axioms Martin.regular_jump
#print axioms Martin.measurableSet_cone
#print axioms Martin.onCone_forall
#print axioms Martin.martinLT_jumpIter
#print axioms Martin.martinLT_const_id
#print axioms Martin.partII_succ_provable_half
#print axioms OracleCode.eval_locality
#print axioms Martin.isOpen_mem_eval
#print axioms Martin.isOpen_jumpP
#print axioms Martin.MartinLE.trans
#print axioms Martin.martinLE_jumpIter_of_le
#print axioms KleenePost.step
#print axioms KleenePost.kleene_post
#print axioms TuringDegree.exists_incomparable
#print axioms TuringDegree.not_isTotal_le
#print axioms Martin.exists_onCone_of_cover
#print axioms Martin.comparability_on_cone
#print axioms Martin.partI_of_cores
#print axioms Martin.partI_Borel_of_cores
#print axioms Martin.exists_uniform_index_on_cone
#print axioms Martin.bounded_implies_constant
#print axioms Martin.partI_of_bounded
#print axioms Martin.counterexample_escapes
#print axioms Martin.regressive_core_iff_escaping
#print axioms Martin.incomparable_core_iff_escaping
#print axioms Martin.orderPreserving_measurePreserving_or_avoids
#print axioms Martin.orderPreserving_trichotomy
#print axioms Martin.partI_orderPreserving_of_lemmas
#print axioms Martin.counterexample_profile
#print axioms Martin.equivVia_join_uniform
#print axioms Martin.uniformlyTuringInvariant_comp_join
#print axioms Martin.join_realizes
#print axioms Martin.exists_pointed_family_of_onCone
#print axioms Martin.comparison_on_cone
#print axioms Martin.partII_total_of_core
#print axioms Martin.partII_WF_of_core
#print axioms Martin.partII_succ_of_core
#print axioms Martin.martinConjecture_of_cores
#print axioms Martin.turingDeterminacy_isOpen
#print axioms Martin.turingDeterminacy_isClosed
#print axioms Martin.not_constant_and_incomparable
#print axioms Martin.incomparable_core_iff_never
#print axioms Martin.partI_iff_cores
#print axioms Martin.partII_total_iff_core
#print axioms Martin.partII_WF_iff_core
#print axioms Martin.partII_succ_iff_core
#print axioms Martin.partII_iff_cores
#print axioms Martin.martinConjectureAD_iff_cores
#print axioms OracleCode.evaln_sound
#print axioms OracleCode.evaln_complete
#print axioms OracleCode.evaln_prim
#print axioms OracleCode.eval_universal
#print axioms OracleCode.exists_fixedPoint
#print axioms OracleCode.dom_iff_jumpP
#print axioms OracleCode.recursiveIn_jump_of_limit
#print axioms OracleCode.exists_quine
#print axioms OracleCode.jumpApproxN_recursiveIn
#print axioms OracleCode.jumpApproxN_limit
#print axioms OracleCode.jump_limitApprox
#print axioms OracleCode.exists_tableEnc
#print axioms OracleCode.recursiveIn_of_jumpApprox
#print axioms OracleCode.limit_lemma
